Traceback (most recent call last):
  File "/home/nicolasbremond/miniconda3/envs/ke2/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/nicolasbremond/miniconda3/envs/ke2/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/nicolasbremond/miniconda3/envs/ke2/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/nicolasbremond/miniconda3/envs/ke2/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/nicolasbremond/miniconda3/envs/ke2/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/nicolasbremond/miniconda3/envs/ke2/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/nicolasbremond/miniconda3/envs/ke2/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/nicolasbremond/miniconda3/envs/ke2/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# pd.set_option('display.float_format', '{:.1f}'.format)

def variable_creation(filepath):
    
    # Lecture du tableau export_data du fichier filename.
    df = pd.read_excel(filepath, sheet_name="export_data",
                             engine="openpyxl").dropna(how='all')
    df = df.to_numpy()
    
    # Initialisation tableau des variables Ã  importer dans Jupyter.
    dfi = [0]*(df.shape[0])
    for i in range(0,df.shape[0]):

        # Routine pour extraire et enregistrer les valeurs depuis le fichier Excel/Ods
        name_sheet = df[i][2]
        col_use = df[i][3]
        skip_r = df[i][4]-1
        n_row = df[i][5]   
        # Extraction et crÃ©ation de la variable i du tableur --> python (numpy)
        dfi[i] = pd.read_excel(filepath, 
                  sheet_name = name_sheet, 
                  skiprows = skip_r,  
                  nrows= n_row, 
                  usecols = col_use,
                  engine="openpyxl").dropna(how='all')
        dfi[i] = dfi[i].replace(np.nan, '', regex=True)
        globals()[df[i][0]]=dfi[i].round(decimals = 4) 
        
variable_creation(filename)

def pd_df_mef(df,nb_round):
           
    styler = df.style.hide(axis='index')\
    .set_properties(subset=[df.columns[0]],
                    **{'font-weight': '', 'background-color': 'white', 'color': ''})\
    .set_caption('')\
    .format(precision=nb_round)
    
    return styler


------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_209968/663140646.py[0m in [0;36m<cell line: 29>[0;34m()[0m
[1;32m     27[0m         [0mglobals[0m[0;34m([0m[0;34m)[0m[0;34m[[0m[0mdf[0m[0;34m[[0m[0mi[0m[0;34m][0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m][0m[0;34m=[0m[0mdfi[0m[0;34m[[0m[0mi[0m[0;34m][0m[0;34m.[0m[0mround[0m[0;34m([0m[0mdecimals[0m [0;34m=[0m [0;36m4[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     28[0m [0;34m[0m[0m
[0;32m---> 29[0;31m [0mvariable_creation[0m[0;34m([0m[0mfilename[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     30[0m [0;34m[0m[0m
[1;32m     31[0m [0;32mdef[0m [0mpd_df_mef[0m[0;34m([0m[0mdf[0m[0;34m,[0m[0mnb_round[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'filename' is not defined
NameError: name 'filename' is not defined

